export const Films = [
    {
        id: 1,
        img: 'assets/images/film/inception.jpg',
        title: 'Inception',
        year: '2010',
        nation: 'USA',
        rating: '8.8',
        time: '2h 28m',
        type: 'Action, Science Fiction, Adventure',
        info: 'Inception was the film that firmly established Christopher Nolans movie as events. It’s also a masterfully well-made story about Dom Cobb, man who literally makes his living invading the dreams of other people and stealing their secrets. Dom’s job is complicated by the fact that his subconscious mind is also haunted by a very literal version his late wife, Mai Cobb. After years in exile away from his children, Dom is given the chance to return home by the enigmatic Mr.Saito. The catch is that Dom and his crew team have to invade the mind of businessman Robert Michael Fischer and convince him to break up his father emprise.  However, each layer of Roberts mind brings new dangers to Mai and his team. Once they go in, they may not come out. ',
        clip: 'https://www.youtube.com/embed/8hP9D6kZseM'
    },
    {
        id: 2,
        img: 'assets/images/film/minions.jpg',
        title: 'Minions: The Rise of Gru',
        year: '2022',
        nation: 'USA',
        rating: '6.5',
        time: '1h 27m',
        type: 'Animation, Comedy, Family',
        info: 'Minions: The Rise of Gru is a film that Peacock should probably have kept to itself, since it was one of the few animated hits of 2022. But Peacock’s loss is Netflix’s gain as the delightfully silly Despicable Me origin story of Gru unfolds with the child supervillain and his Minions attempting to impress Gru’s idols, the Vicious 6, which includes Belle Bottom, Jean-Clawed, Svengeance, Stronghold, and Nin-chuck. Unfortunately for Gru, his efforts only alienate the Vicious 6 and turn them into his enemies. But with the help of the Vicious 6’s former leader, Wild Knuckles, Gru and the Minions have a fighting chance.',
        clip: 'https://www.youtube.com/embed/6DxjJzmYsXo'
    },
    {
        id: 3,
        img: 'assets/images/film/wwz.jpg',
        title: 'World War Z',
        year: '2013',
        nation: 'USA',
        rating: '7.0',
        time: '1h 56m',
        type: 'Action, Drama, Horror, Science Fiction, Thriller',
        info: 'In case you hadn’t guessed, the Z in World War Z stands for zombie. And unfortunately for Brad Pitt’s Gerry Lane, he finds himself thrust into the middle of an unfolding zombie apocalypse. For the sake of his wife, Karin Lane, and their two daughters, Gerry reluctantly agrees to help U.N. researchers discover the source of the zombie virus in the hopes of finding a vaccine before the entire planet is overrun. It’s a race against time, and Gerry’s efforts may already be too late.',
        clip: 'https://www.youtube.com/embed/OLkb4o-2ehc'
    },
    {
        id: 4,
        img: 'assets/images/film/munich.jpg',
        title: 'Munich: The Edge of War',
        year: '2021',
        nation: 'USA',
        rating: '6.8',
        time: '2h 10m',
        type: 'Drama, History',
        info: 'Two college friends find themselves on opposite sides of a brewing war in this film based on Robert Harris’ 2017 novel Munich, which is set against the backdrop of the tense, 1938 meeting in Munich of the European nations that would eventually find themselves embroiled in the second World War. Jeremy Irons portrays U.K. Prime Minister Neville Chamberlain, while George MacKay and Jannis Niewöhner play the former Oxford University classmates who become reluctant spies.',
        clip: 'https://www.youtube.com/embed/AQ7x8odi-OU'
    },
    {
        id: 5,
        img: 'assets/images/film/day-shift.jpg',
        title: 'Day Shift',
        year: '2022',
        nation: 'USA',
        rating: '6.1',
        time: '1h 53m',
        type: 'Action, Fantasy, Horror',
        info: 'Jamie Foxx is a pool cleaner who moonlights as a vampire hunter in Day Shift, an action-horror film that also features Dave Franco and Snoop Dogg in supporting roles. The film is directed J.J. Perry, the award-winning stunt coordinator on recent installments of the Fast & Furious films, and that pedigree is apparent in the movie’s impressive fight sequences. Fast-paced and explosive with plenty of humor, the film is a fun popcorn flick that doesn’t ask you to think too much — just to sit back and enjoy the action.',
        clip: 'https://www.youtube.com/embed/GN_IwBptKi4'
    },
    {
        id: 6,
        img: 'assets/images/film/Ted.jpg',
        title: 'Ted',
        year: '2012',
        nation: 'USA',
        rating: '6.9',
        time: '1h 46m',
        type: 'Comedy, Fantasy',
        info: 'Family Guy creator and star Seth MacFarlane made his live-action directorial debut with Ted, a film where he plays the titular teddy bear. When John Bennett was a child, he made a wish for Ted to come to life and be his best friend. Inexplicably, John’s wish came true. But as adults, John’s lifelong friendship with Ted is getting a little toxic. With the encouragement of his girlfriend, Lori Collins, John encourages Ted to move out and start his own life. And that’s just what he does. But Ted’s bond with John isn’t easily broken, and he drags his friend into more chaotic events that threaten to destroy not only John’s relationship with Lori, but also his connection with Ted.',
        clip: 'https://www.youtube.com/embed/9fbo_pQvU7M'
    },
    {
        id: 7,
        img: 'assets/images/film/shrek.jpg',
        title: 'Shrek Forever After',
        year: '2010',
        nation: 'USA',
        rating: '6.3',
        time: '1h 35m',
        type: 'Comedy, Adventure, Fantasy, Animation, Family',
        info: 'Thanks to the success of Puss In Boots: The Last Wish, fans are revisiting the final Shrek film, Shrek Forever After, on Netflix. Mike Myers once again reprises his role as Shrek, who laments that he has become a domesticated ogre after to his marriage to Princess Fiona and the arrival of their rambunctious kids. When Rumpelstiltskin offers Shrek a chance to be a true ogre again, his magical powers create an alternate world where Shrek was never born and the kingdom is ruled with an iron fist by Rumpelstiltskin himself. To put things right, Shrek will have to reconnect with greatly altered versions of Fiona, Donkey, and Puss in Boots.',
        clip: 'https://www.youtube.com/embed/osvQ1qRSc3s'
    },
    {
        id: 8,
        img: 'assets/images/film/chupa.jpg',
        title: 'Chupa',
        year: '2023',
        nation: 'USA',
        rating: '5.5',
        time: '1h 35m',
        type: 'Adventure, Fantasy, Family',
        info: 'If you’ve ever heard of the legend of the chupacabra, then you know that these goat-sucking fiends aren’t exactly cuddly. At least that’s what we thought before Chupa. In this charming adventure, young Alex goes to Mexico to visit his family in the wake of his father’s death. Soon enough, Alex finds a lost chupacabra cub that he takes in and nurtures. Meanwhile, an American scientist, Richard Quinn, will stop at nothing to find the cub and its mother, and somehow, Alex must find a way to protect his new friend.',
        clip: 'https://www.youtube.com/embed/ViKnrHjzgn4'
    },
    {
        id: 9,
        img: 'assets/images/film/the-sea-beast.jpg',
        title: 'The Sea Beast',
        year: '2022',
        nation: 'USA',
        rating: '7.0',
        time: '1h 55m',
        type: 'Animation, Adventure, Family, Fantasy',
        info: 'Chris Williams, the co-director of Disney’s Big Hero 6 and Moana, takes the helm on the animated high-seas adventure The Sea Beast about a young girl who stows away on a famous monster-hunting ship, only to discover that everything she thought she knew about monsters and hunters might be wrong. Zaris-Angel Hator portrays aspiring monster-hunter Maisie, while Karl Urban voices legendary hunter Jacob Holland in this all-ages feature that’s exciting, funny, and much deeper than its premise suggests.',
        clip: 'https://www.youtube.com/embed/P-E-IGQCsPo'
    },
    {
        id: 10,
        img: 'assets/images/film/enola.jpg',
        title: 'Enola Holmes',
        year: '2020',
        nation: 'USA',
        rating: '6.6',
        time: '2h 03m',
        type: 'Action, Adventure, Mystery, Comedy, Crime',
        info: 'Millie Bobby Brown shines as the title character in this action-packed, fun-filled twist on the classic Sir Arthur Conan Doyle stories. When her mother turns up mysteriously missing, teenage Enola Holmes hits the trail to find her — something her more famous brother, Sherlock Holmes, is simply too preoccupied to do. As she sniffs out clues, Enola discovers she might just have as much as, or even more of, a knack for this sleuthing thing than her brother, slowly uncovering a dangerous conspiracy that threatens to rattle the English aristocracy.',
        clip: 'https://www.youtube.com/embed/1d0Zf9sXlHk'
    },
    {
        id: 11,
        img: 'assets/images/film/pinocchio.jpg',
        title: 'Pinocchio',
        year: '2022',
        nation: 'USA',
        rating: '7.6',
        time: '1h 57m',
        type: 'Animation, Fantasy, Drama, Music',
        info: 'One of Hollywood most visionary filmmakers turns his attention to one of the most beloved tales in children’s literature in Guillermo del Toro’s Pinocchio, a stop-motion animated adaptation of Carlo Collodi’s 1883 novel The Adventures of Pinocchio. Featuring the voices of Ewan McGregor, David Bradley, and Gregory Mann, as Jiminy Cricket, Gepetto, and Pinocchio, respectively, the film chronicles the marionette Pinocchio’s quest to become a living boy — a journey that brings him through one adventure after another. The star-filled voice cast also includes John Turturro, Ron Perlman, Finn Wolfhard, Cate Blanchett, Tim Blake Nelson, Christoph Waltz, and Tilda Swinton, among others. Some reviewers have named it one of the year’s best films, animated or otherwise.',
        clip: 'https://www.youtube.com/embed/Od2NW1sfRdA'
    },
    {
        id: 12,
        img: 'assets/images/film/bullet-train.jpg',
        title: 'Bullet Train',
        year: '2022',
        nation: 'USA',
        rating: '7.3',
        time: '2h 07m',
        type: 'Action, Comedy, Thriller',
        info: 'Deadpool 2 and Atomic Blonde director David Leitch helms the fast-paced, action-comedy adventure Bullet Train that casts Brad Pitt as a tired assassin who would like nothing more than to retire from the murder game. Unfortunately, his latest mission has him taking on an entire train full of hired killers as it speeds through Japan. Joey King, Aaron Taylor-Johnson, Brian Tyree Henry, Andrew Koji, Hiroyuki Sanada, Michael Shannon, Bad Bunny, and Sandra Bullock round out the film’s ensemble cast.',
        clip: 'https://www.youtube.com/embed/UgTPhaNQTWg'
    },
];